[package]
name = "runtrue-sandbox-volume"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hex.workspace = true
nix.workspace = true
runtrue-sandbox-core.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[lints]
workspace = true
