FROM ubuntu@sha256:3131b4cc82a783df6c9df078f86e01819a13594b865c2cad47bd1bca2b7063bb AS runtime-libs

FROM runtime-libs AS broker-binary
COPY target/release/runtrue-sandbox-broker /broker
RUN chmod 0755 /broker \
    && install -d -m 0750 /image/run/secrets/worker \
    && chown -R 65533:65533 /image/run

FROM scratch

ARG SANDBOXD_BUILD_ID=local
LABEL org.opencontainers.image.revision="${SANDBOXD_BUILD_ID}"

COPY --from=runtime-libs /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libgcc_s.so.1
COPY --from=runtime-libs /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libm.so.6
COPY --from=runtime-libs /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY --from=runtime-libs /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=broker-binary /broker /usr/local/bin/runtrue-sandbox-broker
COPY --from=broker-binary /image/run /run

USER 65533:65533
ENTRYPOINT ["/usr/local/bin/runtrue-sandbox-broker"]
