[package]
name = "runtrue-sandbox-gvisor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
hex.workspace = true
libc.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
runtrue-sandbox-artifact.workspace = true
runtrue-sandbox-oci.workspace = true
runtrue-sandbox-core.workspace = true
runtrue-sandbox-volume.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
